export const PUBLIC_VARS = {
  appName: "Mountlet",
  productionSiteUrl: "https://mountlet.app",
  licenseApiPath: "/api/license",
  reportApiPath: "/api/report",
  githubUrl: "https://github.com/eric-holt/mountlet",
  publicBetaKey: "MTB-BETA2-PUBLC-TRIAL-2Z26X",
  env: {
    licenseApiUrl: "MOUNTLET_LICENSE_API_URL",
    licenseSiteUrl: "MOUNTLET_LICENSE_SITE_URL",
    reportApiUrl: "MOUNTLET_REPORT_API_URL",
    resendApiKey: "RESEND_API_KEY",
    resendFrom: "RESEND_FROM",
    resendReplyTo: "RESEND_REPLY_TO",
    emailFrom: "EMAIL_FROM",
    emailReplyTo: "EMAIL_REPLY_TO",
    reportFrom: "REPORT_FROM",
    reportTo: "REPORT_TO",
    reportGithubToken: "REPORT_GITHUB_TOKEN",
    reportGithubRepo: "REPORT_GITHUB_REPO",
    reportGithubLabels: "REPORT_GITHUB_LABELS",
    stripeSecretKey: "STRIPE_SECRET_KEY",
    stripeWebhookSecret: "STRIPE_WEBHOOK_SECRET",
  },
};
